### ISSUE TITLE
Update marketplace entry

### ISSUE THREAD

**Issue by paulvi** [hanks/Refresh_this_project_plugin_for_eclipse#1]
Please update marketplace entry with feature id for Install button to appear, also please add screenshot

**Comment by hanks** [comment]
Thank you for your comment, I updated the entry and added a git screenshot

**Comment by paulvi** [comment]
http://marketplace.eclipse.org/content/refresh-project

I can't see neither

**Comment by paulvi** [comment]
Now I see awesome animation.

Please update marketplace entry with feature id for Install button to appear.

**Comment by hanks** [comment]
@PaulVI 
I see what you mean, and I add the feature id. Thank you.

**Comment by paulvi** [comment]
it is better now
