### ISSUE TITLE
refactor to show what project is being refreshed

### ISSUE THREAD

**Issue by paulvi** [hanks/Refresh_this_project_plugin_for_eclipse#2]
Status message should say what exact project is being refreshed.

Can `doRefreshAction()` be put inside `run()`  ?

```
        protected IStatus run(IProgressMonitor monitor) {


public int doRefreshAction(IWorkbenchPage page, IProgressMonitor monitor) {
```

**Comment by hanks** [comment]
I pushed the commit for the project name. 

And I checked link <a href="http://stackoverflow.com/questions/7367714/nested-functions-in-java">here</a>. Seems java now does not support easy nested function usage.  Use inner class will be ok, but it is a little tricky.
