### ISSUE TITLE
[question] How did you make animated picture?

### ISSUE THREAD

**Issue by paulvi** [hanks/Refresh_this_project_plugin_for_eclipse#6]
What software to user to record screen-cast in such way?

**Comment by hanks** [comment]
Yeah, Do you think it is fun? lol

I just use QuickTime Player of Mac to record screen as a movie file(*.mov),  and then
use <a href="https://itunes.apple.com/us/app/gif-brewery/id435989461?mt=12">GIF Brewery</a> to transfer mov to gif with some compression options
