### ISSUE TITLE
[question] Have you compared with refresh using native hooks or polling option?

### ISSUE THREAD

**Issue by paulvi** [hanks/Refresh_this_project_plugin_for_eclipse#7]
Window -> Preferences -> General -> Workspace

![refresh-using-native-hooks](https://f.cloud.github.com/assets/1614482/2292741/850c3618-a05e-11e3-872c-74f7784d9d97.PNG)

**Comment by hanks** [comment]
I only checked Refresh on access, and I tried Refresh using native hooks or polling, seems 
not to refresh automatically when I git checkout to other branch.

**Comment by paulvi** [comment]
I just read about AutoRefresher http://marketplace.eclipse.org/content/autorefresher/
They also say, install plugin then enable "Refresh using native hooks". And likely it works on MacOs only. Anyway I don't want to try. It was not updated for 1,5 year. So related to #4 : because there was some old plugin, there is no sense to supporting old Eclipse. Only the latest Eclipse and with highest speed and efficiency

**Comment by hanks** [comment]
ok, i got it~~ add the comment
